# source https://www.focisolutions.com/2020/04/github-actions-deploying-an-angular-app/
name: Teste Build & Deploy

on:
  push:
    branches:
      - main
      - thisShouldDeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: thisShouldDeploy

    - name: Setup Node 20
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:deploy

    - name: Archive build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: deploy_dist
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/angular-demo